### ISSUE TITLE
Add ability to use ws options

### ISSUE THREAD

**Issue by lpinca** [porsager/pws#1]
The exposed interface does not allow to use ws [options](https://github.com/websockets/ws/blob/master/doc/ws.md#new-websocketaddress-protocols-options) so it is not possible, for example, to disable CPU intensive extensions like permessage-deflate.

**Comment by porsager** [comment]
Ah, thanks a lot. I'll add that right away. Would also be nice to be able to set other things like ping, maxTimeout, maxRetries etc that way.

**Comment by porsager** [comment]
I went ahead and allowed an options object that contained pws specific options as well which is passed to the websocket constructer. It might be cleaner to have a specific property for `ws` options, but I think that it's fine not having to check the docs to figure that out - what do you think?

**Comment by lpinca** [comment]
It should be ok if there are no conflicts with property names.

**Comment by Gr8z** [comment]
I love you for this @porsager
