### ISSUE TITLE
pingTimeout option crashes

### ISSUE THREAD

**Issue by denis-sokolov** [porsager/pws#2]
I am using the `pingTimeout` option and when the server does not send a message in a while, just as pws is about to close the connection, it crashes with “Cannot assign to read only property 'code' of object '#<CloseEvent>'”

![image](https://user-images.githubusercontent.com/113721/56077200-f6bb3700-5de1-11e9-8299-3743e8649544.png)

![image](https://user-images.githubusercontent.com/113721/56077182-bbb90380-5de1-11e9-8ce7-7a3843a04af9.png)

Chrome 73.0.3683.103, but [MDN agrees](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent) that the property is read-only.

**Comment by porsager** [comment]
Thanks a lot for bringing this to my attention! :)
