### ISSUE TITLE
v4.0.6 published on npm, repository is still v4.0.5

### ISSUE THREAD

**Issue by reboxer** [porsager/pws#7]
I noticed there was a new release in npm, v4.0.6, but when i came to the repository to see the changes i didn't see them and saw the package.json is still 4.0.5, any reason for not updating the repository?

**Comment by porsager** [comment]
I'm sorry, I forgot to push 😩

**Comment by reboxer** [comment]
it's fine, i assumed that could have happened, thanks 👍
