### ISSUE TITLE
persistent websocket not persisting with pingTimeout set

### ISSUE THREAD

**Issue by ebrensi** [porsager/pws#9]
According to the documentation on the readme of this repo,

>  To prevent this state PWS let's you set a specific timeout after which to force a reconnection if you did not receive any messages from the server.

However, what I observe is that if I set pingTimeout, the socket connection closes after that amount of time and does not re-connect.

**Comment by porsager** [comment]
Oh wow. That's quite the regression. I've fixed it now, released in 4.3.0.

**Comment by ebrensi** [comment]
Thanks!
